version: 0.2

phases:
  install:
    commands:
      - echo "Installing Maven..."
      - mvn --version

  pre_build:
    commands:
      - echo "Building the Maven project..."
      - mvn clean package                # Build the JAR
      - echo "Listing files to verify JAR exists:"
      - ls -l target                     # Ensure JAR is here
      - echo "Logging in to Amazon ECR..."
      - aws --version
      - REPOSITORY_URI=079400934343.dkr.ecr.us-east-1.amazonaws.com/product-registry
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin $REPOSITORY_URI
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')
      - echo "IMAGE_TAG is $IMAGE_TAG"

  build:
    commands:
      - echo "Copying JAR to Docker context..."
      - cp target/Product-App-AWS-0.0.1-SNAPSHOT.jar .    # ensure Docker can see it
      - echo "Building the Docker image..."
      - docker build -t $REPOSITORY_URI:latest -f Dockerfile .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG

  post_build:
    commands:
      - echo "Build completed on $(date)"
      - echo "Pushing Docker images..."
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo "Writing imagedefinitions.json..."
      - DOCKER_CONTAINER_NAME=product-registry
      - printf '[{"name":"%s","imageUri":"%s"}]' $DOCKER_CONTAINER_NAME $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
      - echo "imagedefinitions.json content:"
      - cat imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
    - target/Product-App-AWS-0.0.1-SNAPSHOT.jar
